{
  "copyright": "Thorsten Bylicki - BYLICKILABS",
  "url": "https://Github.com/bylickilabs",
  "email": "bylicki@mail.de",
  "format": "html",
  "license": "mit",
  "theme": "dark-tan-mineral",
  "gravatar": true
}
