name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "* */1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Sutil/snk@v01.00.02
        id: snake-gif
        with:
          github_user_name: bylickilabs
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

          

      - uses: Sutil/snk@v01.00.02
      # crazy-max/ghaction-github-pages@v4

      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE
      
      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
                                                  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
