name: Snake Test CI

on:
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Download Snake SVG
        run: |
          mkdir -p dist
          curl -s "https://snake-graph.vercel.app/api/github-contribution-grid?username=bylickilabs&palette=github-dark-dimmed" -o dist/github-snake-green.svg
          ls -lah dist

      - name: Push to output
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin output || git checkout --orphan output
          git switch output || git checkout -b output
          cp dist/github-snake-green.svg github-snake-green.svg
          git add github-snake-green.svg
          git commit -m "Add snake graphic" || echo "No changes"
          git push origin output
